#!/usr/bin/env bash
#
# Local reproduction of the weaviate-chaos-engineering CI job `rbac-upgrade-journey`
# (.github/workflows/tests.yaml). Generated by the `reproducing-ci-jobs` skill and kept
# here as a worked reference — see .claude/skills/reproducing-ci-jobs/SKILL.md.
#
# It reproduces the job step-for-step: setup an old version with RBAC -> create/check roles
# and import data -> upgrade to the target version (enabling dynamic users) -> re-check ->
# rolling restart -> downgrade back. CI-only steps (checkout, docker login, telemetry,
# upload-artifact) are intentionally omitted; everything load-bearing is preserved in order.
#
# Usage:
#   ./rbac-upgrade-journey.sh                       # prompts for any missing inputs
#   LK8S_INPUTS=./rbac-upgrade-journey.inputs ./rbac-upgrade-journey.sh   # non-interactive
#
# Knobs (see reproduce-lib.sh): LK8S_KEEP=true keeps the cluster up on exit;
# LK8S_MAX_RETRIES=1 fails fast; WEAVIATE_LOCAL_K8S_DIR pins a local checkout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# This sample lives inside weaviate-local-k8s, so default to running its own local-k8s.sh.
: "${WEAVIATE_LOCAL_K8S_DIR:=$REPO_ROOT}"
source "$REPO_ROOT/utilities/reproduce-lib.sh"

# --- Resolve values not derivable from the workflow YAML ------------------------------
# Workflow inputs (on.workflow_call.inputs) + the get-previous-version action output.
WEAVIATE_VERSION=$(lk8s_input WEAVIATE_VERSION         "target/preview Weaviate version (workflow input weaviate_version)")
WEAVIATE_INITIAL_VERSION=$(lk8s_input WEAVIATE_INITIAL_VERSION "previous minor version (get-previous-version action output)")
LSM_ACCESS_STRATEGY=$(lk8s_input LSM_ACCESS_STRATEGY   "PERSISTENCE_LSM_ACCESS_STRATEGY (workflow input lsm_access_strategy)" "mmap")
ASYNC_INDEXING=$(lk8s_input ASYNC_INDEXING             "ASYNC_INDEXING (workflow input async_indexing, default true)" "true")
# Where the chaos test apps live (the job's `run:` steps cd into apps/...).
CHAOS=$(lk8s_input CHAOS_REPO "path to weaviate-chaos-engineering checkout" "$HOME/repos/weaviate-chaos-engineering")

# Job-level env from the workflow.
API_KEY="admin-key"          # WEAVIATE_API_KEY
API_KEY_CUSTOM="custom-key"  # WEAVIATE_API_KEY_CUSTOM
RBAC_CONFIG=/tmp/rbac_config.yaml

LK8S=$(lk8s_bootstrap "${LK8S_REF:-v2}")
lk8s_cleanup_trap "$LK8S"     # `local-k8s.sh clean` on exit (LK8S_KEEP=true to keep)

# The job passes this same VALUES_OVERRIDE to every weaviate-local-k8s step.
write_values_override() {
  lk8s_values_override "$LK8S" <<EOF
env:
  PERSISTENCE_LSM_ACCESS_STRATEGY: ${LSM_ACCESS_STRATEGY}
  RAFT_SNAPSHOT_THRESHOLD: 2
  RAFT_TIMEOUTS_MULTIPLIER: 5
  MEMBERLIST_FAST_FAILURE_DETECTION: true
  ASYNC_INDEXING: ${ASYNC_INDEXING}
EOF
}

# --- Step: Install python dependencies ------------------------------------------------
# CI runs `pip3 install --ignore-installed -r requirements.txt` on a throwaway runner. Locally
# that can corrupt whatever global/pyenv env is active, so install into a dedicated venv and
# activate it for every python3 step below (see lk8s_pip_install).
lk8s_pip_install "$CHAOS/apps/rbac-upgrade-journey/requirements.txt"

# --- Step: Generate RBAC config file (static api keys) --------------------------------
cat > "$RBAC_CONFIG" <<EOF
authentication:
  anonymous_access:
    enabled: false
  apikey:
    enabled: true
    allowed_keys:
    - ${API_KEY}
    - ${API_KEY_CUSTOM}
    users:
    - admin-user
    - custom-user
authorization:
  admin_list:
    enabled: false
  rbac:
    enabled: true
    root_users:
      - admin-user
EOF

# --- Step: Weaviate ${WEAVIATE_INITIAL_VERSION} - setup 3-node cluster ------------------
write_values_override
lk8s_weaviate "$LK8S" setup workers=1 replicas=3 weaviate-version="$WEAVIATE_INITIAL_VERSION" \
  modules=text2vec-contextionary rbac=true auth-config="$RBAC_CONFIG"

# --- Steps: create roles, import data, check roles ------------------------------------
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 create_roles.py --api-key "$API_KEY" )
( cd "$CHAOS/apps/upgrade-journey-raft" && python3 run.py --api-key "$API_KEY_CUSTOM" --admin-api-key "$API_KEY" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 check_roles.py --api-key "$API_KEY" )

# --- Step: Regenerate RBAC config enabling dynamic user management --------------------
cat > "$RBAC_CONFIG" <<EOF
authentication:
  anonymous_access:
    enabled: false
  apikey:
    enabled: true
    allowed_keys:
    - ${API_KEY}
    - ${API_KEY_CUSTOM}
    users:
    - admin-user
    - custom-user
  db_users:
    enabled: true
authorization:
  admin_list:
    enabled: false
  rbac:
    enabled: true
    root_users:
      - admin-user
EOF

# --- Step: Weaviate ${WEAVIATE_VERSION} - upgrade + enable dynamic users ---------------
write_values_override
lk8s_weaviate "$LK8S" upgrade workers=1 replicas=3 weaviate-version="$WEAVIATE_VERSION" \
  modules=text2vec-contextionary rbac=true auth-config="$RBAC_CONFIG"

# --- Steps: post-upgrade checks -------------------------------------------------------
( cd "$CHAOS/apps/upgrade-journey-raft" && python3 checks.py --api-key "$API_KEY_CUSTOM" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 check_roles.py --api-key "$API_KEY" )
( cd "$CHAOS/apps/upgrade-journey-raft" && python3 additional_run.py --api-key "$API_KEY_CUSTOM" --admin-api-key "$API_KEY" && python3 additional_checks.py --api-key "$API_KEY_CUSTOM" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 additional_roles.py --api-key "$API_KEY" && python3 additional_check_roles.py --api-key "$API_KEY" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 create_users.py --api-key "$API_KEY" && python3 check_users.py --api-key "$API_KEY" )

# --- Step: rolling restart, then re-check roles/users/data ----------------------------
( cd "$CHAOS/apps/rbac-upgrade-journey" && ./scripts/restart_and_wait.sh )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 additional_check_roles.py --api-key "$API_KEY" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 check_users.py --api-key "$API_KEY" )
( cd "$CHAOS/apps/upgrade-journey-raft" && python3 additional_checks.py --api-key "$API_KEY_CUSTOM" )

# --- Step: Regenerate RBAC config (static keys again, for downgrade) ------------------
cat > "$RBAC_CONFIG" <<EOF
authentication:
  anonymous_access:
    enabled: false
  apikey:
    enabled: true
    allowed_keys:
    - ${API_KEY}
    - ${API_KEY_CUSTOM}
    users:
    - admin-user
    - custom-user
authorization:
  admin_list:
    enabled: false
  rbac:
    enabled: true
    root_users:
      - admin-user
EOF

# --- Step: Weaviate ${WEAVIATE_INITIAL_VERSION} - downgrade back ------------------------
write_values_override
lk8s_weaviate "$LK8S" upgrade workers=1 replicas=3 weaviate-version="$WEAVIATE_INITIAL_VERSION" \
  modules=text2vec-contextionary rbac=true auth-config="$RBAC_CONFIG"

# --- Steps: post-downgrade checks -----------------------------------------------------
( cd "$CHAOS/apps/upgrade-journey-raft" && python3 additional_checks.py --api-key "$API_KEY_CUSTOM" )
( cd "$CHAOS/apps/rbac-upgrade-journey" && python3 additional_check_roles.py --api-key "$API_KEY" )

lk8s_log "rbac-upgrade-journey reproduced successfully."
