#!/usr/bin/env bash
#
# Local reproduction of the weaviate-e2e-tests CI job `upgrade_cluster`
# (.github/workflows/upgrade-tests.yaml). Generated by the `reproducing-ci-jobs` skill and
# kept here as a worked reference for the harder pattern where the job's real work is a
# CONSUMER-REPO COMPOSITE ACTION (`./.github/actions/version-change`) rather than direct
# `weaviate-local-k8s` steps. This script reproduces the composite's steps in order.
#
# It shows how the skill handles:
#   - recursion into a local composite action (caller `with:` -> composite `inputs.*`)
#   - the composite's multi-line VALUES_OVERRIDE written to $GITHUB_ENV
#   - the `shell: python` step that computes RAFT_UPGRADE -> the `delete-sts` of the 2nd deploy
#   - the nested `./.github/actions/generate-config` composite (inlined)
#   - the two weaviate-local-k8s@v2 steps (Deploy Initial Cluster + Perform upgrade)
#   - the interleaved pre_/post_ pytest steps
#
# By default a FAILED step leaves the cluster UP for debugging (LK8S_KEEP unset). To make CI
# fidelity exact and inspect a failure: just run it — if a step fails the cluster stays up,
# and you'll be told how to reach and later clean it.
#
# Usage:
#   LK8S_INPUTS=./upgrade-cluster.inputs ./upgrade-cluster.sh   # non-interactive
#   ./upgrade-cluster.sh                                        # prompts for missing inputs
# Knobs: LK8S_KEEP=true (always keep) | LK8S_KEEP=false (always clean) | LK8S_MAX_RETRIES=1.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
: "${WEAVIATE_LOCAL_K8S_DIR:=$REPO_ROOT}"
source "$REPO_ROOT/utilities/reproduce-lib.sh"

# --- Resolve values not derivable from the workflow YAML ------------------------------
# Chain: real-version-in-tag (job) -> get-previous-version (action) -> version-change inputs.
WEAVIATE_VERSION=$(lk8s_input WEAVIATE_VERSION         "target version tag under test (job input weaviate_version, resolved)")
REAL_WEAVIATE_VERSION=$(lk8s_input REAL_WEAVIATE_VERSION "real semver of the target (real-version-in-tag output)" "$WEAVIATE_VERSION")
WEAVIATE_INITIAL_VERSION=$(lk8s_input WEAVIATE_INITIAL_VERSION "previous minor version (get-previous-version output)")
NUMBER_NODES=$(lk8s_input NUMBER_NODES "number of nodes (job input number_nodes)" "3")
E2E=$(lk8s_input E2E_REPO "path to weaviate-e2e-tests checkout" "$HOME/repos/weaviate-e2e-tests")

# version-change inputs (from the upgrade_cluster job's `with:`) -> its `Set environment variables` step.
WORKERS="$NUMBER_NODES"
REPLICAS="$NUMBER_NODES"
INITIAL_VERSION="$WEAVIATE_INITIAL_VERSION"
TARGET_VERSION="$WEAVIATE_VERSION"
MODULES="text2vec-model2vec"
ENABLE_BACKUP="true"
PYTEST_MARKER_FILTER="not memory_check"
OPERATION="upgrade"

LK8S=$(lk8s_bootstrap "${LK8S_REF:-v2}")
lk8s_cleanup_trap "$LK8S"     # auto-keeps the cluster on failure (LK8S_KEEP tri-state)

# version-change's multi-line VALUES_OVERRIDE (built line-by-line into $GITHUB_ENV in CI).
write_values_override() {
  lk8s_values_override "$LK8S" <<'EOF'
env:
  QUERY_MAXIMUM_RESULTS: 10005
  ASYNC_INDEXING: true
  EXPERIMENTAL_BACKWARDS_COMPATIBLE_NAMED_VECTORS: true
  LOG_LEVEL: info
  TRACK_VECTOR_DIMENSIONS: true
  PERSISTENCE_HNSW_MAX_LOG_SIZE: 1MB
  PERSISTENCE_HNSW_SNAPSHOT_INTERVAL_SECONDS: 60
  PERSISTENCE_HNSW_DISABLE_SNAPSHOTS: false
  ASYNC_REPLICATION_FREQUENCY: 10s
  MEMBERLIST_FAST_FAILURE_DETECTION: true
EOF
}

# Inlined effect of the nested `./.github/actions/generate-config` composite.
generate_config() {  # $1 = version
  cat > "$E2E/config/default_config.yaml" <<EOF
weaviate_namespace: "weaviate"
weaviate_sut_cluster: localhost
async_indexing: true
datasets_path: "./datasets"
vectorizers:
  - name: vectorizer_1
    type: model2vec
  - name: vectorizer_2
    type: transformers
weaviate_clusters:
    localhost:
        main:
            http_port: 8080
            grpc_port: 50051
            url: http://localhost:8080
            api_key: ""
            version: $1
EOF
}

# Reproduces version-change's `Run Pre/Post-<op> Tests` steps (pytest exit code 5 = no tests).
run_pytest() {  # $1 = marker phase (pre_upgrade/post_upgrade), $2 = junit xml
  local phase="$1" xml="$2" code=0 suffix=""
  [[ -n "$PYTEST_MARKER_FILTER" ]] && suffix=" and $PYTEST_MARKER_FILTER"
  ( cd "$E2E" && timeout 130m pytest tests/upgrade/python_upgrade/ --junit-xml="$xml" \
      -m "not wcs and ${phase}${suffix}" ) || code=$?
  if [[ "$code" == "5" ]]; then lk8s_log "No tests collected for ${phase}, continuing"; return 0; fi
  return "$code"
}

# --- version-change: Install Dependencies ---------------------------------------------
( cd "$E2E" && python -m pip install --upgrade pip && pip install -r requirements.txt )

# --- version-change: Deploy Initial Cluster (weaviate-local-k8s@v2) --------------------
write_values_override
lk8s_weaviate "$LK8S" setup workers="$WORKERS" replicas="$REPLICAS" \
  weaviate-version="$INITIAL_VERSION" modules="$MODULES" enable-backup="$ENABLE_BACKUP"
generate_config "$INITIAL_VERSION"
( cd "$E2E" && cat config/default_config.yaml )

# --- version-change: Run Pre-upgrade tests --------------------------------------------
run_pytest "pre_${OPERATION}" pre-change-results.xml

# --- version-change: Check if raft upgrade (shell: python) -> RAFT_UPGRADE -------------
# Reproduces the composite's python step (operation=upgrade branch): is_raft_upgrade =
# target >= 1.25.0 AND initial < 1.25.0. Feeds delete-sts on the second deploy.
RAFT_UPGRADE=$(python3 - "$INITIAL_VERSION" "$REAL_WEAVIATE_VERSION" <<'PY'
import sys
from packaging import version
raft = version.parse("1.25.0")
initial, target = version.parse(sys.argv[1]), version.parse(sys.argv[2])
print(str(target >= raft and initial < raft).lower())
PY
)
lk8s_log "RAFT_UPGRADE=$RAFT_UPGRADE (delete-sts for the upgrade step)"

# --- version-change: Perform upgrade (weaviate-local-k8s@v2) ---------------------------
write_values_override
lk8s_weaviate "$LK8S" upgrade workers="$WORKERS" replicas="$REPLICAS" \
  weaviate-version="$TARGET_VERSION" modules="$MODULES" enable-backup="$ENABLE_BACKUP" \
  delete-sts="$RAFT_UPGRADE"
generate_config "$TARGET_VERSION"
kubectl get pods -n weaviate || true

# --- version-change: Run Post-upgrade tests -------------------------------------------
run_pytest "post_${OPERATION}" post-change-results.xml

lk8s_log "upgrade_cluster reproduced successfully."
