{
 "title": "Cluster info",
 "tags": [ "weaviate" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Created (Statefulset)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_created{statefulset=\"weaviate\"} * 1000",
     "legendFormat": "{{node}} - {{label_name}}"
    }
   ]
  },
  {
   "title": "Number of classes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (class_name)(vector_index_size))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statefulset Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"weaviate\"}",
     "legendFormat": "Replicas Ready"
    },
    {
     "expr": "kube_statefulset_status_replicas_ready{statefulset=\"weaviate\"} / kube_statefulset_status_replicas{statefulset=\"weaviate\"}",
     "legendFormat": "Percentage Replicas Ready"
    }
   ]
  },
  {
   "title": "Weaviate Namespace Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"weaviate\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\".+2112\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Weaviate Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(1,kube_pod_container_info{container=\"weaviate\"})",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"weaviate\", namespace=\"weaviate\",container!~\"POD|pause\"}",
     "legendFormat": "Heap {{pod}}"
    },
    {
     "expr": "max(container_memory_working_set_bytes{container=\"weaviate\", namespace=\"weaviate\",container!~\"POD|pause\"}) by (pod)",
     "legendFormat": "Working Set {{pod}}"
    },
    {
     "expr": "max(go_memstats_heap_inuse_bytes{container=\"weaviate\", namespace=\"weaviate\",container!~\"POD|pause\"}) by (pod)",
     "legendFormat": "Max Heap - {{pod}}"
    }
   ]
  },
  {
   "title": "OOM Events",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_oom_events_total{ namespace=\"weaviate\", pod=~\"weaviate.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{  namespace=\"weaviate\"}[5m])) by (pod, instance)",
     "legendFormat": "{{pod}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Other Services Memory Usage",
   "type": "stat",
   "description": "Other services container memory usage in GB",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod)(container_memory_working_set_bytes{namespace=\"weaviate\", container!=\"\", container!=\"weaviate\"})) / 1e+9",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Weaviate Container Memory Usage",
   "type": "stat",
   "description": "Weaviate container memory usage in GB",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (pod)(container_memory_working_set_bytes{namespace=\"weaviate\", container=\"weaviate\"})) / 1e+9",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{  namespace=\"weaviate\"}[2m])) by (pod, instance, device)",
     "legendFormat": "Write {{pod}}/{{instance}}/{{device}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"weaviate-.*\",  namespace=\"weaviate\"}[2m])) by (pod, instance, device)",
     "legendFormat": "Read {{pod}}/{{instance}}/{{device}}"
    },
    {
     "expr": "sum(rate(container_fs_io_time_seconds_total[2m])) by (pod, instance, device)",
     "legendFormat": "total seconds {{pod}}/{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(object_count) by (class_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entire Cluster Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(queries_durations_ms_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object count rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(object_count[5m])", "legendFormat": "{{class_name}}/{{shard_name}}" }
   ]
  },
  {
   "title": "Disk storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"weaviate\",persistentvolumeclaim=~\"weaviate-.*\"}",
     "legendFormat": "Available {{instance}}-{{persistentvolumeclaim}}"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"weaviate\",persistentvolumeclaim=~\"weaviate-.*\"}",
     "legendFormat": "Used {{instance}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(queries_durations_ms_count[$__interval])",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Network Traffic (RX/TX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"weaviate-.*\",  namespace=\"weaviate\"}[10m])",
     "legendFormat": "TX {{pod}}/{{instance}}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"weaviate-.*\",  namespace=\"weaviate\"}[10m])",
     "legendFormat": "RX {{pod}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Query performance (p50, p75, p90, p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(queries_durations_ms_bucket[1m])) by (le,class_name,instance))",
     "legendFormat": "{{class_name}} - P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(queries_durations_ms_bucket[1m])) by (le,class_name,instance))",
     "legendFormat": "{{class_name}} - P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(queries_durations_ms_bucket[1m])) by (le,class_name,instance))",
     "legendFormat": "{{class_name}} - P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(queries_durations_ms_bucket[1m])) by (le,class_name,instance))",
     "legendFormat": "{{class_name}} - P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(queries_durations_ms_bucket[1m])) by (le,class_name,instance))",
     "legendFormat": "{{class_name}} - P99"
    },
    {
     "expr": "sum(rate(queries_durations_ms_sum[$__rate_interval]))/sum(rate(queries_durations_ms_count[$__rate_interval]))",
     "legendFormat": "Mean Latency"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{instance}} - CURRENT" },
    { "expr": "process_max_fds", "legendFormat": "{{instance}} - MAX" }
   ]
  },
  {
   "title": "Batch performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(batch_durations_ms_sum{class_name=\"n/a\"}[$__rate_interval])/rate(batch_durations_ms_count{class_name=\"n/a\"}[$__rate_interval])",
     "legendFormat": "{{operation}} {{shard_name}}"
    }
   ]
  },
  { "title": "List of modules", "type": "timeseries", "gridPos": { "h": 4, "w": 6, "x": 12, "y": 45 } },
  { "title": "Recent pod events", "type": "timeseries", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 45 } },
  {
   "title": "Number of tombstones",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "targets": [
    { "expr": "vector_index_tombstones ", "legendFormat": "{{class_name}}/{{shard_name}}" }
   ]
  },
  {
   "title": "Index operation distribution (index, update,delete)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 56 }
  },
  { "title": "400/500 HTTP errors", "type": "timeseries", "gridPos": { "h": 4, "w": 6, "x": 6, "y": 56 } }
 ]
}