{
 "title": "Async Indexing",
 "tags": [ "weaviate" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Queues paused",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(index_queue_paused{})\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Preloaded vectors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(index_queue_preload_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "index_queue_size",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Dequeued vectors per tick (1s)",
   "type": "timeseries",
   "description": "Number of vectors sent to the indexing workers every tick (e.g 1s). This number should be low during imports (e.g 1000) if throttling is enabled, or equal to the 1000 x (the number of cores - 1), if throttling is disabled or there are no imports.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "index_queue_vectors_dequeued ",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Time spent waiting for the workers (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(index_queue_wait_duration_ms_sum[5m])) by (shard_name, target_vector)\n/\nsum(rate(index_queue_wait_duration_ms_count[5m])) by (shard_name, target_vector)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}