{
 "title": "Querying",
 "tags": [ "weaviate" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Query Latency",
   "type": "timeseries",
   "description": "Average query latency per time interval for each class.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(queries_durations_ms_sum{}[$__interval]) / rate(queries_durations_ms_count{}[$__interval])",
     "legendFormat": "{{class_name}} "
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Number of queries per second for each class",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(queries_durations_ms_count{}[$__interval])",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "90th Percentile Query Latency (Estimated)",
   "type": "timeseries",
   "description": "Note the percentiles are calculated from histogram buckets so have an associated error see https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(queries_durations_ms_bucket{}[$__interval])) by (le,class_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Query Latency (Estimated)",
   "type": "timeseries",
   "description": "Note the percentiles are calculated from histogram buckets so have an associated error see https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(queries_durations_ms_bucket{}[$__interval])) by (le,class_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered Query Latency",
   "type": "timeseries",
   "description": "Break down of filtered query latency by operation",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(queries_filtered_vector_durations_ms_sum{operation=\"filter\"}[$__interval]) / rate(queries_filtered_vector_durations_ms_count{operation=\"filter\"}[$__interval])",
     "legendFormat": "{{class_name}}/{{operation}}/{{shard_name}}"
    },
    {
     "expr": "rate(queries_filtered_vector_durations_ms_sum{operation=\"sort\"}[$__interval]) / rate(queries_filtered_vector_durations_ms_count{operation=\"sort\"}[$__interval])",
     "legendFormat": "{{class_name}}/{{operation}}/{{shard_name}}"
    },
    {
     "expr": "rate(queries_filtered_vector_durations_ms_sum{operation=\"vector\"}[$__interval]) / rate(queries_filtered_vector_durations_ms_count{operation=\"vector\"}[$__interval])",
     "legendFormat": "{{class_name}}/{{operation}}/{{shard_name}}"
    },
    {
     "expr": "rate(queries_filtered_vector_durations_ms_sum{operation=\"objects\"}[$__interval]) / rate(queries_filtered_vector_durations_ms_count{operation=\"objects\"}[$__interval])",
     "legendFormat": "{{class_name}}/{{operation}}/{{shard_name}}"
    }
   ]
  },
  {
   "title": "Concurrent Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(concurrent_queries_count{query_type=\"batch\"})",
     "legendFormat": "Batch (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"batch_references\"})",
     "legendFormat": "Batch (References)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"add_object\"})",
     "legendFormat": "Add (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"update_object\"})",
     "legendFormat": "Update (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"merge_object\"})",
     "legendFormat": "Merge (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"delete_object\"})",
     "legendFormat": "Delete (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"add_reference\"})",
     "legendFormat": "Add (Reference)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"update_reference\"})",
     "legendFormat": "Update (Reference)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"delete_reference\"})",
     "legendFormat": "Delete (Reference)"
    }
   ]
  },
  {
   "title": "Concurrent Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(concurrent_queries_count{query_type=\"aggregate\"})",
     "legendFormat": "Aggregate"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"get_graphql\"})",
     "legendFormat": "Get (GraphQL)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"get_object\"})",
     "legendFormat": "Get (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"head_object\"})",
     "legendFormat": "Head (Objects)"
    }
   ]
  }
 ]
}