{
 "title": "SPFresh",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "LSM Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Store Get duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(vector_index_store_operations_durations_ms_sum{operation=\"get\"}[$__interval]) / (rate(vector_index_store_operations_durations_ms_count{operation=\"get\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Put duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(vector_index_store_operations_durations_ms_sum{operation=\"put\"}[$__interval]) / (rate(vector_index_store_operations_durations_ms_count{operation=\"put\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Append duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(vector_index_store_operations_durations_ms_sum{operation=\"append\"}[$__interval]) / (rate(vector_index_store_operations_durations_ms_count{operation=\"append\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Posting size percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vector_index_posting_size_vectors_bucket{}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vector_index_posting_size_vectors_bucket{}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vector_index_posting_size_vectors_bucket{}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vector_index_posting_size_vectors_bucket{}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vector_index_posting_size_vectors_bucket{}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Number of postings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "vector_index_postings{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Centroid Search duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(vector_index_background_operations_durations_ms_sum{operation=\"centroid_search\"}[$__interval]) / (rate(vector_index_background_operations_durations_ms_count{operation=\"centroid_search\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Background Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pending Split operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "vector_index_pending_background_operations{operation=\"split\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Split duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(vector_index_background_operations_durations_ms_sum{operation=\"split\"}[$__interval]) / (rate(vector_index_background_operations_durations_ms_count{operation=\"split\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Reassign operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "vector_index_pending_background_operations{operation=\"reassign\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reassign duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(vector_index_background_operations_durations_ms_sum{operation=\"reassign\"}[$__interval]) / (rate(vector_index_background_operations_durations_ms_count{operation=\"reassign\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Insert / Delete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Inserts per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(vector_index_operations{operation=\"create\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"create\"}[$__interval]) / (rate(vector_index_durations_ms_count{operation=\"create\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(vector_index_operations{operation=\"delete\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletion duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"delete\"}[$__interval]) / (rate(vector_index_durations_ms_count{operation=\"delete\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}