{
 "title": "Tombstone Analysis",
 "tags": [ "weaviate" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Active Tombstones in HNSW index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vector_index_tombstones{}",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Vector Index Statistics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_index_operations{operation=\"create\"})",
     "legendFormat": "Vectors Inserted"
    },
    {
     "expr": "sum(vector_index_operations{operation=\"delete\"})",
     "legendFormat": "Vectors Deleted"
    },
    {
     "expr": "sum(vector_index_operations{operation=\"create\"}) - ignoring(operation) sum(vector_index_operations{operation=\"delete\"})",
     "legendFormat": "Net Vectors"
    }
   ]
  },
  {
   "title": "Weaviate goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"weaviate\"}",
     "legendFormat": "Weaviate goroutines"
    }
   ]
  },
  {
   "title": "Tombstone Reassign Neighbors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "tombstone_reassign_neighbors", "legendFormat": "Reassign - {{shard_name}}" }
   ]
  },
  {
   "title": "Find Local & Global Entrypoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "tombstone_find_global_entrypoint",
     "legendFormat": "Global Entrypoint - {{shard_name}}"
    },
    {
     "expr": "tombstone_find_global_entrypoint",
     "legendFormat": "Local Entrypoint - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Tombstone Delete List Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "tombstone_delete_list_size",
     "legendFormat": "{{class_name}} - {{shard_name}}"
    }
   ]
  },
  {
   "title": "Unexpected Tombstones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "vector_index_tombstone_unexpected_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}