{
 "title": "Vector Index",
 "tags": [ "weaviate" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Vector Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vector_index_size{}",
     "legendFormat": "{{class_name}} / {{shard_name}}"
    }
   ]
  },
  {
   "title": "Vector Index Maintenance Operations (Sync & Async)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(vector_index_maintenance_durations_ms_sum{}[$__interval]) / rate(vector_index_maintenance_durations_ms_count{}[$__interval])",
     "legendFormat": "{{step}} ({{class_name}}/{{shard_name}})"
    }
   ]
  },
  {
   "title": "Insert Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"create\"}[$__interval])/rate(vector_index_durations_ms_count{operation=\"create\"}[$__interval])",
     "legendFormat": "{{step}} ({{class_name}}/{{shard_name}})"
    },
    {
     "expr": "concurrent_goroutines{class_name=\"object batcher\"}",
     "legendFormat": "Concurrent goroutines"
    }
   ]
  },
  {
   "title": "Delete Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_index_durations_ms_sum{operation=\"delete\"}[$__interval])/rate(vector_index_durations_ms_count{operation=\"delete\"}[$__interval])",
     "legendFormat": "{{step}} ({{class_name}}/{{shard_name}})"
    }
   ]
  }
 ]
}