apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: weaviate
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "400m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: weaviate
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
  - port: 11434
    name: http
    targetPort: http
    protocol: TCP