on:
  push:

jobs:
    run-weaviate-local-k8s:
      runs-on: ubuntu-latest
      name: Test the weaviate-local-k8s action
      steps:
        - uses: actions/checkout@v4
        - id: foo
          uses: weaviate/weaviate-local-k8s@main
          with:
            workers: '3'
            replicas: '5'
            weaviate-version: '1.24.3'